### PR TITLE
CartesianPoint, ImagePoint, Sensor skeleton

### PR DESCRIPTION
**Pull request by ihumphrey-usgs**

### CODE REVIEW

**Comment by kberryUSGS** [comment]
If these are going to be classes instead of structs again, can you include accessors to grab, for example, just X, just Y, and just Z from a `CartesianPoint`?

**Comment by ihumphrey-usgs** [comment]
@kberryUSGS We decided to go with structs inside of a "sensorcore.h" header

**Comment by ihumphrey-usgs** [comment]
(Also, to whoever merges this) **please Squash and merge**

**Comment by kberryUSGS** [comment]
@ihumphrey-usgs This looks great thank you!

**Pull request merged**
