### PR TITLE
DO NOT MERGE...started code for the SensorUtils library.

### PR DESCRIPTION
**Pull request by twilson271828**
I will add more tomorrow.

### CODE REVIEW

**Comment by jlaura** [comment]
@twilson271828 Three thoughts:

- This should be using CMake, not a Makefile.
- This library has nothing to do with CSM, so no namespace
- This is mergeable with those fixes, so no reason to flag with DO NOT MERGE. We need to be doing lots of small PRs / merges to avoid development bottlenecks (for example, it is much easier to merge your code and start a Python wrapper or add a few methods than to wait or pull this PR local).

**Comment by jessemapel** [comment]
@makaylas and I are going to put in a cmake build system this morning. I'm fine with merging this with the makefile and then we'll swap it out for cmake.

**Comment by jlaura** [comment]
Why merge and then later scrub the history? Why merge with no tests (when we are writing test first)? I guess, I am not sure what is added in this PR that is not going to be removed shortly?

**Comment by makaylas** [comment]
Also your code should be in a src directory.

**Comment by makaylas** [comment]
I'm going to kill this PR because there is another PR that covers the same code along with CMake and CTest

**Pull request closed without merging**
