### PR TITLE
Added virtual methods to the SensorModel class

### PR DESCRIPTION
**Pull request by twilson271828**
Question:  Is there any need for an implementation file for a pure virtual class like this?
Also, what namespace should this go into (if any)?

### CODE REVIEW

**Comment by jessemapel** [comment]
I think we can kill the source file for this. @twilson271828 as you said it's pure virtual.

**Comment by jessemapel** [comment]
@twilson271828 Do you want to remove that file in this PR or a different one?

**Comment by twilson271828** [comment]
I'll do it in this one.

**Comment by jessemapel** [comment]
Once that's done feel free to merge it once checks pass :+1:

**Pull request merged**
